function h(a){throw a;}var j=true,l=null,m=false;function aa(a){return function(b){this[a]=b}}function ba(a){return function(){return this[a]}}var p,ca=ca||{},q=this;function u(a,b,c){a=a.split(".");c=c||q;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}}function da(a,b){for(var c=a.split("."),d=b||q,f;f=c.shift();)if(d[f])d=d[f];else return l;return d}function ea(){}
function fa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ga(a){return fa(a)=="array"}function ha(a){var b=fa(a);return b=="array"||b=="object"&&typeof a.length=="number"}function v(a){return typeof a=="string"}function ia(a){return fa(a)=="function"}function ja(a){a=fa(a);return a=="object"||a=="array"||a=="function"}function w(a){return a[ka]||(a[ka]=++la)}var ka="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),la=0;
function ma(a,b){var c=b||q;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(c,f)}}else return function(){return a.apply(c,arguments)}}function na(a){var b=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,b);return a.apply(this,c)}}var oa=Date.now||function(){return+new Date};
function pa(a,b){var c=b||{},d;for(d in c){var f=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),f)}return a}function x(a,b){function c(){}c.prototype=b.prototype;a.g=b.prototype;a.prototype=new c};function qa(a){this.stack=Error().stack||"";if(a)this.message=String(a)}x(qa,Error);qa.prototype.name="CustomError";function ra(a){for(var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,c)}return a}function y(a,b){if(b)return a.replace(sa,"&amp;").replace(ta,"&lt;").replace(ua,"&gt;").replace(va,"&quot;");else{if(!wa.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(sa,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(ta,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(ua,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(va,"&quot;");return a}}
var sa=/&/g,ta=/</g,ua=/>/g,va=/\"/g,wa=/[&<>\"]/;function xa(a,b,c){a=c!==undefined?a.toFixed(c):String(a);c=a.indexOf(".");if(c==-1)c=a.length;return Array(Math.max(0,b-c)+1).join("0")+a}
function ya(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(d.length,f.length),g=0;c==0&&g<e;g++){var i=d[g]||"",k=f[g]||"",n=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var r=n.exec(i)||["","",""],o=s.exec(k)||["","",""];if(r[0].length==0&&o[0].length==0)break;c=za(r[1].length==0?0:parseInt(r[1],10),o[1].length==0?0:parseInt(o[1],10))||za(r[2].length==0,o[2].length==0)||za(r[2],o[2])}while(c==
0)}return c}function za(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};function Aa(a,b){b.unshift(a);qa.call(this,ra.apply(l,b));b.shift();this.Zc=a}x(Aa,qa);Aa.prototype.name="AssertionError";function Ba(a,b){if(!a){var c=Array.prototype.slice.call(arguments,2),d="Assertion failed";if(b){d+=": "+b;var f=c}h(new Aa(""+d,f||[]))}return a}function Ca(a){h(new Aa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};var z=Array.prototype,A=z.indexOf?function(a,b,c){Ba(a.length!=l);return z.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:c<0?Math.max(0,a.length+c):c;if(v(a)){if(!v(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Da=z.forEach?function(a,b,c){Ba(a.length!=l);z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=v(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};
function Ea(a,b){var c=A(a,b),d;if(d=c>=0){Ba(a.length!=l);z.splice.call(a,c,1)}return d}function Fa(){return z.concat.apply(z,arguments)}function Ga(a){if(ga(a))return Fa(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function Ha(a){Ba(a.length!=l);return z.splice.apply(a,Ia(arguments,1))}function Ia(a,b,c){Ba(a.length!=l);return arguments.length<=2?z.slice.call(a,b):z.slice.call(a,b,c)};var Ja,Ka,La,Ma;function Na(){return q.navigator?q.navigator.userAgent:l}Ma=La=Ka=Ja=m;var Oa;if(Oa=Na()){var Pa=q.navigator;Ja=Oa.indexOf("Opera")==0;Ka=!Ja&&Oa.indexOf("MSIE")!=-1;La=!Ja&&Oa.indexOf("WebKit")!=-1;Ma=!Ja&&!La&&Pa.product=="Gecko"}var Qa=Ja,B=Ka,C=Ma,D=La,Ra=q.navigator,Sa=(Ra&&Ra.platform||"").indexOf("Mac")!=-1,Ta;
a:{var Ua="",Va;if(Qa&&q.opera){var Wa=q.opera.version;Ua=typeof Wa=="function"?Wa():Wa}else{if(C)Va=/rv\:([^\);]+)(\)|;)/;else if(B)Va=/MSIE\s+([^\);]+)(\)|;)/;else if(D)Va=/WebKit\/(\S+)/;if(Va){var Xa=Va.exec(Na());Ua=Xa?Xa[1]:""}}if(B){var Ya,Za=q.document;Ya=Za?Za.documentMode:undefined;if(Ya>parseFloat(Ua)){Ta=String(Ya);break a}}Ta=Ua}var $a={};function E(a){return $a[a]||($a[a]=ya(Ta,a)>=0)};var ab,bb=!B||E("9");B&&E("9");function cb(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function db(a){var b=cb(a),c;c=Ia(arguments,1);for(var d=0,f=0;f<c.length;f++)if(!(A(b,c[f])>=0)){b.push(c[f]);d++}c=d==c.length;a.className=b.join(" ");return c}function eb(a){var b=cb(a),c;c=Ia(arguments,1);for(var d=0,f=0;f<b.length;f++)if(A(c,b[f])>=0){Ha(b,f--,1);d++}c=d==c.length;a.className=b.join(" ");return c}function fb(a,b){var c=!(A(cb(a),b)>=0);c?db(a,b):eb(a,b);return c};function gb(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function hb(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function ib(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function jb(a,b){var c;if(c=b in a)delete a[b];return c}var kb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function lb(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var f=0;f<kb.length;f++){b=kb[f];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}};function mb(a){return a?new nb(ob(a)):ab||(ab=new nb)}function F(a){return v(a)?document.getElementById(a):a}
function pb(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(!D||document.compatMode=="CSS1Compat"||E("528"))&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var f=0,e=0,g;g=a[e];e++)if(b==g.nodeName)d[f++]=g;d.length=f;return d}else return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(e=f=0;g=a[e];e++){b=g.className;if(typeof b.split=="function"&&A(b.split(/\s+/),c)>=0)d[f++]=
g}d.length=f;return d}else return a}function qb(a,b){gb(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in rb)a.setAttribute(rb[d],c);else a[d]=c})}var rb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function sb(a,b){var c=b[0],d=b[1];if(!bb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',y(d.name),'"');if(d.type){c.push(' type="',y(d.type),'"');var f={};lb(f,d);d=f;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);if(d)if(v(d))c.className=d;else ga(d)?db.apply(l,[c].concat(d)):qb(c,d);b.length>2&&tb(a,c,b,2);return c}
function tb(a,b,c,d){function f(g){if(g)b.appendChild(v(g)?a.createTextNode(g):g)}for(d=d;d<c.length;d++){var e=c[d];ha(e)&&!(ja(e)&&e.nodeType>0)?Da(ub(e)?Ga(e):e,f):f(e)}}function G(){return sb(document,arguments)}function vb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function wb(a){return a&&a.parentNode?a.parentNode.removeChild(a):l}function xb(a,b){for(;a&&a.nodeType!=1;)a=b?a.nextSibling:a.previousSibling;return a}function ob(a){return a.nodeType==9?a:a.ownerDocument||a.document}
function H(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{vb(a);a.appendChild(ob(a).createTextNode(b))}}function ub(a){if(a&&typeof a.length=="number")if(ja(a))return typeof a.item=="function"||typeof a.item=="string";else if(ia(a))return typeof a.item=="function";return m}function nb(a){this.J=a||q.document||document}p=nb.prototype;
p.C=function(a){return v(a)?this.J.getElementById(a):a};p.sa=function(){return sb(this.J,arguments)};p.createElement=function(a){return this.J.createElement(a)};p.createTextNode=function(a){return this.J.createTextNode(a)};p.appendChild=function(a,b){a.appendChild(b)};function I(){}I.prototype.rb=m;I.prototype.s=function(){if(!this.rb){this.rb=j;this.f()}};I.prototype.f=function(){};var yb;!B||E("9");var zb=B&&!E("8");function J(a,b){this.type=a;this.currentTarget=this.target=b}x(J,I);p=J.prototype;p.f=function(){delete this.type;delete this.target;delete this.currentTarget};p.Q=m;p.ma=j;p.stopPropagation=function(){this.Q=j};p.preventDefault=function(){this.ma=m};function K(a,b){a&&this.ia(a,b)}x(K,J);p=K.prototype;p.target=l;p.relatedTarget=l;p.offsetX=0;p.offsetY=0;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.button=0;p.keyCode=0;p.charCode=0;p.ctrlKey=m;p.altKey=m;p.shiftKey=m;p.metaKey=m;p.Jc=m;p.L=l;
p.ia=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(C)try{d=d.nodeName&&d}catch(f){d=l}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||0;
this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Jc=Sa?a.metaKey:a.ctrlKey;this.L=a;delete this.ma;delete this.Q};p.stopPropagation=function(){K.g.stopPropagation.call(this);if(this.L.stopPropagation)this.L.stopPropagation();else this.L.cancelBubble=j};
p.preventDefault=function(){K.g.preventDefault.call(this);var a=this.L;if(a.preventDefault)a.preventDefault();else{a.returnValue=m;if(zb)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}}};p.f=function(){K.g.f.call(this);this.relatedTarget=this.currentTarget=this.target=this.L=l};function Ab(){}var Bb=0;p=Ab.prototype;p.key=0;p.Y=m;p.mb=m;p.ia=function(a,b,c,d,f,e){if(ia(a))this.Db=j;else if(a&&a.handleEvent&&ia(a.handleEvent))this.Db=m;else h(Error("Invalid listener argument"));this.W=a;this.Lb=b;this.src=c;this.type=d;this.capture=!!f;this.Aa=e;this.mb=m;this.key=++Bb;this.Y=m};p.handleEvent=function(a){if(this.Db)return this.W.call(this.Aa||this.src,a);return this.W.handleEvent.call(this.W,a)};function L(a,b){this.Gb=b;this.N=[];if(a>this.Gb)h(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var c=0;c<a;c++)this.N.push(this.da())}x(L,I);p=L.prototype;p.I=l;p.qb=l;function Cb(a){if(a.N.length)return a.N.pop();return a.da()}function M(a,b){a.N.length<a.Gb?a.N.push(b):a.Ra(b)}p.da=function(){return this.I?this.I():{}};p.Ra=function(a){if(this.qb)this.qb(a);else if(ja(a))if(ia(a.s))a.s();else for(var b in a)delete a[b]};
p.f=function(){L.g.f.call(this);for(var a=this.N;a.length;)this.Ra(a.pop());delete this.N};var Db;var Eb=(Db="ScriptEngine"in q&&q.ScriptEngine()=="JScript")?q.ScriptEngineMajorVersion()+"."+q.ScriptEngineMinorVersion()+"."+q.ScriptEngineBuildVersion():"0";var Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb;
(function(){function a(){return{i:0,l:0}}function b(){return[]}function c(){function o(t){return g.call(o.src,o.key,t)}return o}function d(){return new Ab}function f(){return new K}var e=Db&&!(ya(Eb,"5.7")>=0),g;Kb=function(o){g=o};if(e){Fb=function(){return Cb(i)};Gb=function(o){M(i,o)};Hb=function(){return Cb(k)};Ib=function(o){M(k,o)};Jb=function(){return Cb(n)};Lb=function(){M(n,c())};Mb=function(){return Cb(s)};Nb=function(o){M(s,o)};Ob=function(){return Cb(r)};Pb=function(o){M(r,o)};var i=new L(0,
600);i.I=a;var k=new L(0,600);k.I=b;var n=new L(0,600);n.I=c;var s=new L(0,600);s.I=d;var r=new L(0,600);r.I=f}else{Fb=a;Gb=ea;Hb=b;Ib=ea;Jb=c;Lb=ea;Mb=d;Nb=ea;Ob=f;Pb=ea}})();var Qb={},N={},O={},Rb={};
function P(a,b,c,d,f){if(b)if(ga(b)){for(var e=0;e<b.length;e++)P(a,b[e],c,d,f);return l}else{d=!!d;var g=N;b in g||(g[b]=Fb());g=g[b];if(!(d in g)){g[d]=Fb();g.i++}g=g[d];var i=w(a),k;g.l++;if(g[i]){k=g[i];for(e=0;e<k.length;e++){g=k[e];if(g.W==c&&g.Aa==f){if(g.Y)break;return k[e].key}}}else{k=g[i]=Hb();g.i++}e=Jb();e.src=a;g=Mb();g.ia(c,e,a,b,d,f);c=g.key;e.key=c;k.push(g);Qb[c]=g;O[i]||(O[i]=Hb());O[i].push(g);if(a.addEventListener){if(a==q||!a.ob)a.addEventListener(b,e,d)}else a.attachEvent(Sb(b),
e);return c}else h(Error("Invalid event type"))}function Tb(a,b,c,d,f){if(ga(b)){for(var e=0;e<b.length;e++)Tb(a,b[e],c,d,f);return l}d=!!d;a=Ub(a,b,d);if(!a)return m;for(e=0;e<a.length;e++)if(a[e].W==c&&a[e].capture==d&&a[e].Aa==f)return Q(a[e].key);return m}
function Q(a){if(!Qb[a])return m;var b=Qb[a];if(b.Y)return m;var c=b.src,d=b.type,f=b.Lb,e=b.capture;if(c.removeEventListener){if(c==q||!c.ob)c.removeEventListener(d,f,e)}else c.detachEvent&&c.detachEvent(Sb(d),f);c=w(c);f=N[d][e][c];if(O[c]){var g=O[c];Ea(g,b);g.length==0&&delete O[c]}b.Y=j;f.Hb=j;Vb(d,e,c,f);delete Qb[a];return j}
function Vb(a,b,c,d){if(!d.Ea)if(d.Hb){for(var f=0,e=0;f<d.length;f++)if(d[f].Y){var g=d[f].Lb;g.src=l;Lb(g);Nb(d[f])}else{if(f!=e)d[e]=d[f];e++}d.length=e;d.Hb=m;if(e==0){Ib(d);delete N[a][b][c];N[a][b].i--;if(N[a][b].i==0){Gb(N[a][b]);delete N[a][b];N[a].i--}if(N[a].i==0){Gb(N[a]);delete N[a]}}}}
function Wb(a,b,c){var d=0,f=b==l,e=c==l;c=!!c;if(a==l)gb(O,function(k){for(var n=k.length-1;n>=0;n--){var s=k[n];if((f||b==s.type)&&(e||c==s.capture)){Q(s.key);d++}}});else{a=w(a);if(O[a]){a=O[a];for(var g=a.length-1;g>=0;g--){var i=a[g];if((f||b==i.type)&&(e||c==i.capture)){Q(i.key);d++}}}}return d}function Ub(a,b,c){var d=N;if(b in d){d=d[b];if(c in d){d=d[c];a=w(a);if(d[a])return d[a]}}return l}function Sb(a){if(a in Rb)return Rb[a];return Rb[a]="on"+a}
function Xb(a,b,c,d,f){var e=1;b=w(b);if(a[b]){a.l--;a=a[b];if(a.Ea)a.Ea++;else a.Ea=1;try{for(var g=a.length,i=0;i<g;i++){var k=a[i];if(k&&!k.Y)e&=Yb(k,f)!==m}}finally{a.Ea--;Vb(c,d,b,a)}}return Boolean(e)}function Yb(a,b){var c=a.handleEvent(b);a.mb&&Q(a.key);return c}
Kb(function(a,b){if(!Qb[a])return j;var c=Qb[a],d=c.type,f=N;if(!(d in f))return j;f=f[d];var e,g;if(yb===undefined)yb=B&&!q.addEventListener;if(yb){e=b||da("window.event");var i=j in f,k=m in f;if(i){if(e.keyCode<0||e.returnValue!=undefined)return j;a:{var n=m;if(e.keyCode==0)try{e.keyCode=-1;break a}catch(s){n=j}if(n||e.returnValue==undefined)e.returnValue=j}}n=Ob();n.ia(e,this);e=j;try{if(i){for(var r=Hb(),o=n.currentTarget;o;o=o.parentNode)r.push(o);g=f[j];g.l=g.i;for(var t=r.length-1;!n.Q&&t>=
0&&g.l;t--){n.currentTarget=r[t];e&=Xb(g,r[t],d,j,n)}if(k){g=f[m];g.l=g.i;for(t=0;!n.Q&&t<r.length&&g.l;t++){n.currentTarget=r[t];e&=Xb(g,r[t],d,m,n)}}}else e=Yb(c,n)}finally{if(r){r.length=0;Ib(r)}n.s();Pb(n)}return e}d=new K(b,this);try{e=Yb(c,d)}finally{d.s()}return e});function Zb(){}x(Zb,I);p=Zb.prototype;p.ob=j;p.Fa=l;p.eb=aa("Fa");p.addEventListener=function(a,b,c,d){P(this,a,b,c,d)};p.removeEventListener=function(a,b,c,d){Tb(this,a,b,c,d)};
p.dispatchEvent=function(a){a=a;if(v(a))a=new J(a,this);else if(a instanceof J)a.target=a.target||this;else{var b=a;a=new J(a.type,this);lb(a,b)}b=1;var c,d=a.type,f=N;if(d in f){f=f[d];d=j in f;var e;if(d){c=[];for(e=this;e;e=e.Fa)c.push(e);e=f[j];e.l=e.i;for(var g=c.length-1;!a.Q&&g>=0&&e.l;g--){a.currentTarget=c[g];b&=Xb(e,c[g],a.type,j,a)&&a.ma!=m}}if(m in f){e=f[m];e.l=e.i;if(d)for(g=0;!a.Q&&g<c.length&&e.l;g++){a.currentTarget=c[g];b&=Xb(e,c[g],a.type,m,a)&&a.ma!=m}else for(c=this;!a.Q&&c&&
e.l;c=c.Fa){a.currentTarget=c;b&=Xb(e,c,a.type,m,a)&&a.ma!=m}}a=Boolean(b)}else a=j;return a};p.f=function(){Zb.g.f.call(this);Wb(this);this.Fa=l};var $b=q.window;function ac(a){if(typeof a.za=="function")return a.za();if(v(a))return a.split("");if(ha(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return hb(a)}function bc(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(ha(a)||v(a))Da(a,b,c);else{var d;if(typeof a.ha=="function")d=a.ha();else if(typeof a.za!="function")if(ha(a)||v(a)){d=[];for(var f=a.length,e=0;e<f;e++)d.push(e);d=d}else d=ib(a);else d=void 0;f=ac(a);e=f.length;for(var g=0;g<e;g++)b.call(c,f[g],d&&d[g],a)}};var cc="StopIteration"in q?q.StopIteration:Error("StopIteration");function dc(){}dc.prototype.next=function(){h(cc)};dc.prototype.Oa=function(){return this};function ec(a){if(a instanceof dc)return a;if(typeof a.Oa=="function")return a.Oa(m);if(ha(a)){var b=0,c=new dc;c.next=function(){for(;;){if(b>=a.length)h(cc);if(b in a)return a[b++];else b++}};return c}h(Error("Not implemented"))}
function fc(a,b,c){if(ha(a))try{Da(a,b,c)}catch(d){if(d!==cc)h(d)}else{a=ec(a);try{for(;;)b.call(c,a.next(),undefined,a)}catch(f){if(f!==cc)h(f)}}};function gc(a){this.u={};this.b=[];var b=arguments.length;if(b>1){if(b%2)h(Error("Uneven number of arguments"));for(var c=0;c<b;c+=2)this.Z(arguments[c],arguments[c+1])}else if(a){if(a instanceof gc){b=a.ha();c=a.za()}else{b=ib(a);c=hb(a)}for(var d=0;d<b.length;d++)this.Z(b[d],c[d])}}p=gc.prototype;p.i=0;p.Ja=0;p.za=function(){hc(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.u[this.b[b]]);return a};p.ha=function(){hc(this);return this.b.concat()};
p.clear=function(){this.u={};this.Ja=this.i=this.b.length=0};function hc(a){if(a.i!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];if(Object.prototype.hasOwnProperty.call(a.u,d))a.b[c++]=d;b++}a.b.length=c}if(a.i!=a.b.length){var f={};for(c=b=0;b<a.b.length;){d=a.b[b];if(!Object.prototype.hasOwnProperty.call(f,d)){a.b[c++]=d;f[d]=1}b++}a.b.length=c}}function ic(a,b,c){if(Object.prototype.hasOwnProperty.call(a.u,b))return a.u[b];return c}
p.Z=function(a,b){if(!Object.prototype.hasOwnProperty.call(this.u,a)){this.i++;this.b.push(a);this.Ja++}this.u[a]=b};p.r=function(){return new gc(this)};p.Oa=function(a){hc(this);var b=0,c=this.b,d=this.u,f=this.Ja,e=this,g=new dc;g.next=function(){for(;;){if(f!=e.Ja)h(Error("The map has changed since the iterator was created"));if(b>=c.length)h(cc);var i=c[b++];return a?i:d[i]}};return g};function jc(a){return kc(a||arguments.callee.caller,[])}
function kc(a,b){var c=[];if(A(b,a)>=0)c.push("[...circular reference...]");else if(a&&b.length<50){c.push(lc(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){f>0&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":e=e;break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=lc(e))?e:"[fn]";break;default:e=typeof e}if(e.length>40)e=e.substr(0,40)+"...";c.push(e)}b.push(a);c.push(")\n");try{c.push(kc(a.caller,
b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")}function lc(a){a=String(a);if(!mc[a]){var b=/function ([^\(]+)/.exec(a);mc[a]=b?b[1]:"[Anonymous]"}return mc[a]}var mc={};function nc(a,b,c,d,f){this.reset(a,b,c,d,f)}nc.prototype.Mc=0;nc.prototype.wb=l;nc.prototype.vb=l;var oc=0;nc.prototype.reset=function(a,b,c,d,f){this.Mc=typeof f=="number"?f:oc++;this.cd=d||oa();this.la=a;this.$c=b;this.Yc=c;delete this.wb;delete this.vb};nc.prototype.Ob=aa("la");function R(a){this.Gc=a}R.prototype.w=l;R.prototype.la=l;R.prototype.B=l;R.prototype.Bb=l;function pc(a,b){this.name=a;this.value=b}pc.prototype.toString=ba("name");var qc=new pc("SEVERE",1E3),rc=new pc("WARNING",900),sc=new pc("CONFIG",700),tc=new pc("FINE",500),uc=new pc("FINEST",300);R.prototype.Ob=aa("la");function vc(a){if(a.la)return a.la;if(a.w)return vc(a.w);Ca("Root logger has no level set.");return l}
R.prototype.log=function(a,b,c){if(a.value>=vc(this).value){a=this.wc(a,b,c);for(b=this;b;){c=b;var d=a;if(c.Bb)for(var f=0,e=void 0;e=c.Bb[f];f++)e(d);b=b.w}}};
R.prototype.wc=function(a,b,c){var d=new nc(a,String(b),this.Gc);if(c){d.wb=c;var f;var e=arguments.callee.caller;try{var g,i=da("window.location.href");g=typeof c=="string"?{message:c,name:"Unknown error",lineNumber:"Not available",fileName:i,stack:"Not available"}:!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:c.lineNumber||c.Xc||"Not available",fileName:c.fileName||c.filename||c.sourceURL||i,stack:c.stack||"Not available"}:c;f="Message: "+y(g.message)+'\nUrl: <a href="view-source:'+
g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+y(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+y(jc(e)+"-> ")}catch(k){f="Exception trying to expose exception! You win, we lose. "+k}d.vb=f}return d};function S(a,b,c){a.log(tc,b,c)}var wc={},xc=l;function yc(a){if(!xc){xc=new R("");wc[""]=xc;xc.Ob(sc)}var b;if(!(b=wc[a])){b=new R(a);var c=a.lastIndexOf("."),d=a.substr(c+1);c=yc(a.substr(0,c));if(!c.B)c.B={};c.B[d]=b;b.w=c;b=wc[a]=b}return b};function zc(){}zc.prototype.qa=l;function Ac(){return Bc(Cc)}var Cc;function Dc(){}x(Dc,zc);function Bc(a){return(a=Ec(a))?new ActiveXObject(a):new XMLHttpRequest}function Fc(a){var b={};if(Ec(a)){b[0]=j;b[1]=j}return b}Dc.prototype.Za=l;
function Ec(a){if(!a.Za&&typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{new ActiveXObject(d);return a.Za=d}catch(f){}}h(Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.Za}Cc=new Dc;function Gc(){if(C){this.H={};this.Ma={};this.Ha=[]}}Gc.prototype.e=yc("goog.net.xhrMonitor");Gc.prototype.wa=C;function Hc(a,b){if(a.wa){var c=v(b)?b:ja(b)?w(b):"";a.e.log(uc,"Pushing context: "+b+" ("+c+")",void 0);a.Ha.push(c)}}function Ic(a){if(a.wa){var b=a.Ha.pop();a.e.log(uc,"Popping context: "+b,void 0);Jc(a,b)}}function Kc(a,b){if(a.wa){var c=w(b);S(a.e,"Opening XHR : "+c);for(var d=0;d<a.Ha.length;d++){var f=a.Ha[d];Lc(a,a.H,f,c);Lc(a,a.Ma,c,f)}}}
function Jc(a,b){var c=a.Ma[b],d=a.H[b];if(c&&d){a.e.log(uc,"Updating dependent contexts",void 0);Da(c,function(f){Da(d,function(e){Lc(this,this.H,f,e);Lc(this,this.Ma,e,f)},this)},a)}}function Lc(a,b,c,d){b[c]||(b[c]=[]);A(b[c],d)>=0||b[c].push(d)}var T=new Gc;function U(a){this.headers=new gc;this.$=a||l}x(U,Zb);U.prototype.e=yc("goog.net.XhrIo");var Mc=[];function Nc(a,b,c,d,f,e){var g=new U;Mc.push(g);b&&P(g,"complete",b);P(g,"ready",na(Oc,g));if(e)g.pa=Math.max(0,e);g.send(a,c,d,f)}function Oc(a){a.s();Ea(Mc,a)}p=U.prototype;p.A=m;p.d=l;p.La=l;p.Fb="";p.Eb="";p.ja=0;p.ka="";p.Va=m;p.Ba=m;p.$a=m;p.O=m;p.pa=0;p.R=l;
p.send=function(a,b,c,d){if(this.d)h(Error("[goog.net.XhrIo] Object is active with another request"));b=b||"GET";this.Fb=a;this.ka="";this.ja=0;this.Eb=b;this.Va=m;this.A=j;this.d=this.$?Bc(this.$):new Ac;this.La=this.$?this.$.qa||(this.$.qa=Fc(this.$)):Cc.qa||(Cc.qa=Fc(Cc));Kc(T,this.d);this.d.onreadystatechange=ma(this.Jb,this);try{S(this.e,V(this,"Opening Xhr"));this.$a=j;this.d.open(b,a,j);this.$a=m}catch(f){S(this.e,V(this,"Error opening Xhr: "+f.message));Pc(this,5,f);return}a=c||"";var e=this.headers.r();
d&&bc(d,function(i,k){e.Z(k,i)});b=="POST"&&!Object.prototype.hasOwnProperty.call(e.u,"Content-Type")&&e.Z("Content-Type","application/x-www-form-urlencoded;charset=utf-8");bc(e,function(i,k){this.d.setRequestHeader(k,i)},this);try{if(this.R){$b.clearTimeout(this.R);this.R=l}if(this.pa>0){S(this.e,V(this,"Will abort after "+this.pa+"ms if incomplete"));this.R=$b.setTimeout(ma(this.Uc,this),this.pa)}S(this.e,V(this,"Sending request"));this.Ba=j;this.d.send(a);this.Ba=m}catch(g){S(this.e,V(this,"Send error: "+
g.message));Pc(this,5,g)}};p.dispatchEvent=function(a){if(this.d){Hc(T,this.d);try{return U.g.dispatchEvent.call(this,a)}finally{Ic(T)}}else return U.g.dispatchEvent.call(this,a)};p.Uc=function(){if(typeof ca!="undefined")if(this.d){this.ka="Timed out after "+this.pa+"ms, aborting";this.ja=8;S(this.e,V(this,this.ka));this.dispatchEvent("timeout");this.abort(8)}};function Pc(a,b,c){a.A=m;if(a.d){a.O=j;a.d.abort();a.O=m}a.ka=c;a.ja=b;Qc(a);Rc(a)}
function Qc(a){if(!a.Va){a.Va=j;a.dispatchEvent("complete");a.dispatchEvent("error")}}p.abort=function(a){if(this.d&&this.A){S(this.e,V(this,"Aborting"));this.A=m;this.O=j;this.d.abort();this.O=m;this.ja=a||7;this.dispatchEvent("complete");this.dispatchEvent("abort");Rc(this)}};p.f=function(){if(this.d){if(this.A){this.A=m;this.O=j;this.d.abort();this.O=m}Rc(this,j)}U.g.f.call(this)};p.Jb=function(){!this.$a&&!this.Ba&&!this.O?this.Ic():Sc(this)};p.Ic=function(){Sc(this)};
function Sc(a){if(a.A)if(typeof ca!="undefined")if(a.La[1]&&Tc(a)==4&&Uc(a)==2)S(a.e,V(a,"Local request error detected and ignored"));else if(a.Ba&&Tc(a)==4)$b.setTimeout(ma(a.Jb,a),0);else{a.dispatchEvent("readystatechange");if(Tc(a)==4){S(a.e,V(a,"Request complete"));a.A=m;var b;a:switch(Uc(a)){case 0:case 200:case 204:case 304:b=j;break a;default:b=m}if(b){a.dispatchEvent("complete");a.dispatchEvent("success")}else{a.ja=6;var c;try{c=Tc(a)>2?a.d.statusText:""}catch(d){S(a.e,"Can not get status: "+
d.message);c=""}a.ka=c+" ["+Uc(a)+"]";Qc(a)}Rc(a)}}}function Rc(a,b){if(a.d){var c=a.d,d=a.La[0]?ea:l;a.d=l;a.La=l;if(a.R){$b.clearTimeout(a.R);a.R=l}if(!b){Hc(T,c);a.dispatchEvent("ready");Ic(T)}if(T.wa){var f=w(c);S(T.e,"Closing XHR : "+f);delete T.Ma[f];for(var e in T.H){Ea(T.H[e],f);T.H[e].length==0&&delete T.H[e]}}try{c.onreadystatechange=d}catch(g){a.e.log(qc,"Problem encountered resetting onreadystatechange: "+g.message,void 0)}}}function Tc(a){return a.d?a.d.readyState:0}
function Uc(a){try{return Tc(a)>2?a.d.status:-1}catch(b){a.e.log(rc,"Can not get status: "+b.message,void 0);return-1}}
function Vc(a,b){if(a.d){var c=a.d.responseText;if(b&&c.indexOf(b)==0)c=c.substring(b.length);var d;a:{c=String(c);var f;f=/^\s*$/.test(c)?m:/^[\],:{}\s\u2028\u2029]*$/.test(c.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""));if(f)try{d=eval("("+c+")");break a}catch(e){}h(Error("Invalid JSON string: "+c))}return d}}
function V(a,b){return b+" ["+a.Eb+" "+a.Fb+" "+Uc(a)+"]"};function Wc(a,b){switch(b){case 1:return a%4==0&&(a%100!=0||a%400==0)?29:28;case 5:case 8:case 10:case 3:return 30}return 31}function W(a,b,c,d,f,e){if(v(a)){this.q=a==Xc?b:0;this.o=a==Yc?b:0;this.m=a==Zc?b:0;this.t=a==$c?b:0;this.v=a==ad?b:0;this.z=a==bd?b:0}else{this.q=a||0;this.o=b||0;this.m=c||0;this.t=d||0;this.v=f||0;this.z=e||0}}
W.prototype.Ia=function(a){var b=Math.min(this.q,this.o,this.m,this.t,this.v,this.z),c=Math.max(this.q,this.o,this.m,this.t,this.v,this.z);if(b<0&&c>0)return l;if(!a&&b==0&&c==0)return"PT0S";c=[];b<0&&c.push("-");c.push("P");if(this.q||a)c.push(Math.abs(this.q)+"Y");if(this.o||a)c.push(Math.abs(this.o)+"M");if(this.m||a)c.push(Math.abs(this.m)+"D");if(this.t||this.v||this.z||a){c.push("T");if(this.t||a)c.push(Math.abs(this.t)+"H");if(this.v||a)c.push(Math.abs(this.v)+"M");if(this.z||a)c.push(Math.abs(this.z)+
"S")}return c.join("")};W.prototype.r=function(){return new W(this.q,this.o,this.m,this.t,this.v,this.z)};var Xc="y",Yc="m",Zc="d",$c="h",ad="n",bd="s";W.prototype.add=function(a){this.q+=a.q;this.o+=a.o;this.m+=a.m;this.t+=a.t;this.v+=a.v;this.z+=a.z};
function cd(a,b,c){if(typeof a=="number"){this.a=new Date(a,b||0,c||1);dd(this,c||1)}else if(ja(a)){this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate());dd(this,a.getDate())}else{this.a=new Date;this.a.setHours(0);this.a.setMinutes(0);this.a.setSeconds(0);this.a.setMilliseconds(0)}}p=cd.prototype;p.M=0;p.ya=3;p.r=function(){var a=new cd(this.a);a.M=this.M;a.ya=this.ya;return a};p.getFullYear=function(){return this.a.getFullYear()};p.getYear=function(){return this.getFullYear()};p.getMonth=function(){return this.a.getMonth()};
p.getDate=function(){return this.a.getDate()};p.getTime=function(){return this.a.getTime()};p.getDay=function(){return this.a.getDay()};p.getUTCHours=function(){return this.a.getUTCHours()};p.getTimezoneOffset=function(){return this.a.getTimezoneOffset()};p.Z=function(a){this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate())};p.setFullYear=function(a){this.a.setFullYear(a)};p.setMonth=function(a){this.a.setMonth(a)};p.setDate=function(a){this.a.setDate(a)};
p.add=function(a){if(a.q||a.o){var b=this.getMonth()+a.o+a.q*12,c=this.getYear()+Math.floor(b/12);b%=12;if(b<0)b+=12;var d=Math.min(Wc(c,b),this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}if(a.m){a=new Date((new Date(this.getYear(),this.getMonth(),this.getDate(),12)).getTime()+a.m*864E5);this.setDate(1);this.setFullYear(a.getFullYear());this.setMonth(a.getMonth());this.setDate(a.getDate());dd(this,a.getDate())}};
p.Ia=function(a,b){var c;if(b){c=this.getTimezoneOffset();if(c==0)c="Z";else{var d=Math.abs(c)/60,f=Math.floor(d);c=(c>0?"-":"+")+xa(f,2)+":"+xa((d-f)*60,2)}c=c}else c="";return[this.getFullYear(),xa(this.getMonth()+1,2),xa(this.getDate(),2)].join(a?"-":"")+c};p.toString=function(){return this.Ia()};function dd(a,b){if(a.getDate()!=b)a.a.setUTCHours(a.a.getUTCHours()+(a.getDate()<b?1:-1))}p.valueOf=function(){return this.a.valueOf()};function ed(a,b){if(C){a.setAttribute("role",b);a.ad=b}};function fd(a,b,c,d,f){if(!B&&!(D&&E("525")))return j;if(Sa&&f)return gd(a);if(f&&!d)return m;if(!c&&(b==17||b==18))return m;if(B&&d&&b==a)return m;switch(a){case 13:return j;case 27:return!D}return gd(a)}
function gd(a){if(a>=48&&a<=57)return j;if(a>=96&&a<=106)return j;if(a>=65&&a<=90)return j;if(D&&a==0)return j;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return j;default:return m}};function hd(a,b){if(a){this.Da&&this.detach();this.j=a;this.Ca=P(this.j,"keypress",this,b);this.ab=P(this.j,"keydown",this.zc,b,this);this.Da=P(this.j,"keyup",this.Ac,b,this)}}x(hd,Zb);p=hd.prototype;p.j=l;p.Ca=l;p.ab=l;p.Da=l;p.G=-1;p.D=-1;
var id={"3":13,"12":144,"63232":38,"63233":40,"63234":37,"63235":39,"63236":112,"63237":113,"63238":114,"63239":115,"63240":116,"63241":117,"63242":118,"63243":119,"63244":120,"63245":121,"63246":122,"63247":123,"63248":44,"63272":46,"63273":36,"63275":35,"63276":33,"63277":34,"63289":144,"63302":45},jd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},kd={61:187,
59:186},ld=B||D&&E("525");p=hd.prototype;p.zc=function(a){if(D&&(this.G==17&&!a.ctrlKey||this.G==18&&!a.altKey))this.D=this.G=-1;if(ld&&!fd(a.keyCode,this.G,a.shiftKey,a.ctrlKey,a.altKey))this.handleEvent(a);else this.D=C&&a.keyCode in kd?kd[a.keyCode]:a.keyCode};p.Ac=function(){this.D=this.G=-1};
p.handleEvent=function(a){var b=a.L,c,d;if(B&&a.type=="keypress"){c=this.D;d=c!=13&&c!=27?b.keyCode:0}else if(D&&a.type=="keypress"){c=this.D;d=b.charCode>=0&&b.charCode<63232&&gd(c)?b.charCode:0}else if(Qa){c=this.D;d=gd(c)?b.keyCode:0}else{c=b.keyCode||this.D;d=b.charCode||0;if(Sa&&d==63&&!c)c=191}var f=c,e=b.keyIdentifier;if(c)if(c>=63232&&c in id)f=id[c];else{if(c==25&&a.shiftKey)f=9}else if(e&&e in jd)f=jd[e];a=f==this.G;this.G=f;b=new md(f,d,a,b);try{this.dispatchEvent(b)}finally{b.s()}};
p.C=ba("j");p.detach=function(){if(this.Ca){Q(this.Ca);Q(this.ab);Q(this.Da);this.Da=this.ab=this.Ca=l}this.j=l;this.D=this.G=-1};p.f=function(){hd.g.f.call(this);this.detach()};function md(a,b,c,d){d&&this.ia(d,void 0);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}x(md,K);var nd={fc:["BC","AD"],ec:["Before Christ","Anno Domini"],gc:["J","F","M","A","M","J","J","A","S","O","N","D"],mc:["J","F","M","A","M","J","J","A","S","O","N","D"],aa:["January","February","March","April","May","June","July","August","September","October","November","December"],lc:["January","February","March","April","May","June","July","August","September","October","November","December"],jc:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],oc:["Jan","Feb","Mar","Apr","May",
"Jun","Jul","Aug","Sep","Oct","Nov","Dec"],sc:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],qc:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],lb:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],pc:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],hc:["S","M","T","W","T","F","S"],nc:["S","M","T","W","T","F","S"],kc:["Q1","Q2","Q3","Q4"],ic:["1st quarter","2nd quarter","3rd quarter","4th quarter"],cc:["AM","PM"],ib:["EEEE, y MMMM dd","y MMMM d","y MMM d","yyyy-MM-dd"],
rc:["HH:mm:ss v","HH:mm:ss z","HH:mm:ss","HH:mm"],dc:{Md:"M/d",MMMMd:"MMMM d",MMMd:"MMM d"},jb:0,Na:[5,6],kb:3},od={fc:["BC","AD"],ec:["Before Christ","Anno Domini"],gc:["J","F","M","A","M","J","J","A","S","O","N","D"],mc:["J","F","M","A","M","J","J","A","S","O","N","D"],aa:["January","February","March","April","May","June","July","August","September","October","November","December"],lc:["January","February","March","April","May","June","July","August","September","October","November","December"],
jc:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],oc:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],sc:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],qc:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],lb:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],pc:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],hc:["S","M","T","W","T","F","S"],nc:["S","M","T","W","T","F","S"],kc:["Q1","Q2","Q3","Q4"],ic:["1st quarter",
"2nd quarter","3rd quarter","4th quarter"],cc:["AM","PM"],ib:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],rc:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],dc:{Md:"M/d",MMMMd:"MMMM d",MMMd:"MMM d"},jb:6,Na:[5,6],kb:2};function pd(a,b){a.style.display=b?"":"none"};function qd(a){this.Ab=a}x(qd,I);var rd=new L(0,100);function sd(a,b,c,d,f,e){if(ga(c))for(var g=0;g<c.length;g++)sd(a,b,c[g],d,f,e);else{b=P(b,c,d||a,f||m,e||a.Ab||a);if(a.b)a.b[b]=j;else if(a.F){a.b=Cb(rd);a.b[a.F]=j;a.F=l;a.b[b]=j}else a.F=b}return a}
function td(a,b,c,d,f,e){if(a.F||a.b)if(ga(c))for(var g=0;g<c.length;g++)td(a,b,c[g],d,f,e);else{a:{d=d||a;e=e||a.Ab||a;f=!!f;if(b=Ub(b,c,f))for(c=0;c<b.length;c++)if(b[c].W==d&&b[c].capture==f&&b[c].Aa==e){b=b[c];break a}b=l}if(b){b=b.key;Q(b);if(a.b)jb(a.b,b);else if(a.F==b)a.F=l}}return a}function ud(a){if(a.b){for(var b in a.b){Q(b);delete a.b[b]}M(rd,a.b);a.b=l}else a.F&&Q(a.F)}qd.prototype.f=function(){qd.g.f.call(this);ud(this)};qd.prototype.handleEvent=function(){h(Error("EventHandler.handleEvent not implemented"))};function vd(){}(function(a){a.xb=function(){return a.Ec||(a.Ec=new a)}})(vd);vd.prototype.cb=0;vd.xb();function X(a){this.c=a||mb();this.Lc=wd}x(X,Zb);X.prototype.Dc=vd.xb();var wd=l;p=X.prototype;p.Cb=l;p.U=m;p.j=l;p.Lc=l;p.Fc=l;p.w=l;p.B=l;p.ra=l;p.bc=m;p.C=ba("j");function xd(a){return a.T||(a.T=new qd(a))}p.eb=function(a){if(this.w&&this.w!=a)h(Error("Method not supported"));X.g.eb.call(this,a)};p.sa=function(){this.j=this.c.createElement("div")};
function yd(a,b){if(a.U)h(Error("Component already rendered"));else if(b){a.bc=j;if(!a.c||a.c.J!=ob(b))a.c=mb(b);a.ua(b);a.xa()}else h(Error("Invalid element to decorate"))}p.ua=aa("j");p.xa=function(){this.U=j;zd(this,function(a){!a.U&&a.C()&&a.xa()})};p.ga=function(){zd(this,function(a){a.U&&a.ga()});this.T&&ud(this.T);this.U=m};
p.f=function(){X.g.f.call(this);this.U&&this.ga();if(this.T){this.T.s();delete this.T}zd(this,function(a){a.s()});!this.bc&&this.j&&wb(this.j);this.w=this.Fc=this.j=this.ra=this.B=l};function zd(a,b,c){a.B&&Da(a.B,b,c)}
p.removeChild=function(a,b){if(a){var c=v(a)?a:a.Cb||(a.Cb=":"+(a.Dc.cb++).toString(36)),d;if(this.ra&&c){d=this.ra;d=c in d?d[c]:void 0;d=d||l}else d=l;a=d;if(c&&a){jb(this.ra,c);Ea(this.B,a);if(b){a.ga();a.j&&wb(a.j)}c=a;if(c==l)h(Error("Unable to set parent component"));c.w=l;X.g.eb.call(c,l)}}if(!a)h(Error("Child is not in parent component"));return a};function Y(a,b,c){X.call(this,c);this.p=b||od;this.Wc=this.p.lb;this.a=new cd(a);this.a.ya=this.p.kb;this.a.M=this.p.jb;this.h=this.a.r();this.h.setDate(1);this.Ka=["","","","","","",""];this.Ka[this.p.Na[0]]="goog-date-picker-wkend-start";this.Ka[this.p.Na[1]]="goog-date-picker-wkend-end";this.V={};this.c=c||mb()}x(Y,X);p=Y.prototype;p.Pb=j;p.Qc=j;p.vc=j;p.fb=j;p.Rb=j;p.Pa=j;p.Qb=j;p.Sc=m;p.pb=l;p.va=l;p.Sa=l;var Ad=0;p=Y.prototype;p.Kb=function(){this.h.add(new W(Yc,-1));Z(this)};
p.Ib=function(){this.h.add(new W(Yc,1));Z(this)};p.Kc=function(){this.h.add(new W(Xc,-1));Z(this)};p.Hc=function(){this.h.add(new W(Xc,1));Z(this)};p.Nb=function(){this.setDate(new cd)};p.Mb=function(){this.Pa&&this.setDate(l)};p.getDate=ba("a");
p.setDate=function(a){var b=a!=this.a&&!(a&&this.a&&a.getFullYear()==this.a.getFullYear()&&a.getMonth()==this.a.getMonth()&&a.getDate()==this.a.getDate());this.a=a&&new cd(a);if(a){this.h.Z(this.a);this.h.setDate(1)}Z(this);this.dispatchEvent(new Bd("select",this,this.a));b&&this.dispatchEvent(new Bd("change",this,this.a))};
p.ua=function(a){Y.g.ua.call(this,a);a.className="goog-date-picker";var b=this.c.createElement("table"),c=this.c.createElement("thead"),d=this.c.createElement("tbody"),f=this.c.createElement("tfoot");ed(d,"grid");d.tabIndex="0";this.gb=d;this.Vb=f;var e=this.c.createElement("tr");e.className="goog-date-picker-head";if(this.va=e){for(var g=this.va;g.firstChild;)g.removeChild(g.firstChild);var i,k;if(this.Sc){i=this.c.createElement("td");i.colSpan=this.fb?1:2;$(this,i,"\u00ab",this.Kb);g.appendChild(i);
i=this.c.createElement("td");i.colSpan=this.fb?6:5;i.className="goog-date-picker-monthyear";g.appendChild(i);this.Ta=i;i=this.c.createElement("td");$(this,i,"\u00bb",this.Ib);g.appendChild(i)}else{var n=this.p.ib[0].toLowerCase();i=this.c.createElement("td");i.colSpan=5;$(this,i,"\u00ab",this.Kb);this.K=$(this,i,"",this.Nc,"goog-date-picker-month");$(this,i,"\u00bb",this.Ib);k=this.c.createElement("td");k.colSpan=3;$(this,k,"\u00ab",this.Kc);this.ea=$(this,k,"",this.Rc,"goog-date-picker-year");$(this,
k,"\u00bb",this.Hc);if(n.indexOf("y")<n.indexOf("m")){g.appendChild(k);g.appendChild(i)}else{g.appendChild(i);g.appendChild(k)}}}c.appendChild(e);this.k=[];for(i=0;i<7;i++){e=this.c.createElement("tr");this.k[i]=[];for(k=0;k<8;k++){g=this.c.createElement(k==0||i==0?"th":"td");if((k==0||i==0)&&k!=i){g.className=k==0?"goog-date-picker-week":"goog-date-picker-wday";ed(g,k==0?"rowheader":"columnheader")}e.appendChild(g);this.k[i][k]=g}d.appendChild(e)}e=this.c.createElement("tr");e.className="goog-date-picker-foot";
g=this.Sa=e;vb(g);i=this.c.createElement("td");i.colSpan=2;i.className="goog-date-picker-today-cont";k=pa("Today");this.tb=$(this,i,k,this.Nb);g.appendChild(i);i=this.c.createElement("td");i.colSpan=4;g.appendChild(i);i=this.c.createElement("td");i.colSpan=2;i.className="goog-date-picker-none-cont";k=pa("None");this.sb=$(this,i,k,this.Mb);g.appendChild(i);pd(this.tb,this.Qb);pd(this.sb,this.Pa);pd(this.Vb,this.Qb||this.Pa);f.appendChild(e);b.cellSpacing="0";b.cellPadding="0";b.appendChild(c);b.appendChild(d);
b.appendChild(f);a.appendChild(b);if(this.C()){if(this.Rb)for(b=0;b<7;b++)H(this.k[0][b+1],this.Wc[((b+this.h.M+7)%7+1)%7]);pd(this.k[0][0].parentNode,this.Rb)}Z(this);a.tabIndex=0};p.sa=function(){Y.g.sa.call(this);this.ua(this.C())};p.xa=function(){Y.g.xa.call(this);var a=xd(this);sd(a,this.gb,"click",this.xc);sd(a,Cd(this,this.C()),"key",this.yc)};p.ga=function(){Y.g.ga.call(this);this.S();for(var a in this.V)this.V[a].s();this.V={}};
p.f=function(){Y.g.f.call(this);this.sb=this.tb=this.ea=this.Ta=this.K=this.Sa=this.va=this.Vb=this.gb=this.k=l};p.xc=function(a){if(a.target.tagName=="TD"){var b,c=-2,d=-2;for(b=a.target;b;b=b.previousSibling,c++);for(b=a.target.parentNode;b;b=b.previousSibling,d++);this.setDate(this.n[d][c].r())}};
p.yc=function(a){var b,c;switch(a.keyCode){case 33:a.preventDefault();b=-1;break;case 34:a.preventDefault();b=1;break;case 37:a.preventDefault();c=-1;break;case 39:a.preventDefault();c=1;break;case 38:a.preventDefault();c=-7;break;case 40:a.preventDefault();c=7;break;case 36:a.preventDefault();this.Nb();case 46:a.preventDefault();this.Mb();default:return}if(this.a){a=this.a.r();a.add(new W(0,b,c))}else{a=this.h.r();a.setDate(1)}this.setDate(a)};
p.Nc=function(a){a.stopPropagation();a=[];for(var b=0;b<12;b++)a.push(this.p.aa[b]);Dd(this,this.K,a,this.Bc,this.p.aa[this.h.getMonth()])};p.Rc=function(a){a.stopPropagation();a=[];for(var b=this.h.getFullYear()-5,c=0;c<11;c++)a.push(String(b+c));Dd(this,this.ea,a,this.Cc,String(this.h.getFullYear()))};p.Bc=function(a){a=a;for(var b=-1;a;a=xb(a.previousSibling,m),b++);this.h.setMonth(b);Z(this);this.K.focus&&this.K.focus()};
p.Cc=function(a){if(a.firstChild.nodeType==3){this.h.setFullYear(Number(a.firstChild.nodeValue));Z(this)}this.ea.focus()};
function Dd(a,b,c,d,f){a.S();var e=a.c.createElement("div");e.className="goog-date-picker-menu";a.X=l;for(var g=a.c.createElement("ul"),i=0;i<c.length;i++){var k=a.c.sa("li",l,c[i]);if(c[i]==f)a.X=k;g.appendChild(k)}e.appendChild(g);e.style.left=b.offsetLeft+b.parentNode.offsetLeft+"px";e.style.top=b.offsetTop+"px";e.style.width=b.clientWidth+"px";a.K.parentNode.appendChild(e);a.P=e;if(!a.X)a.X=g.firstChild;a.X.className="goog-date-picker-menu-selected";a.bb=d;b=xd(a);sd(b,a.P,"click",a.yb);sd(b,
Cd(a,a.P),"key",a.zb);sd(b,a.c.J,"click",a.S);e.tabIndex=0;e.focus()}p.yb=function(a){a.stopPropagation();this.S();this.bb&&this.bb(a.target)};
p.zb=function(a){a.stopPropagation();var b,c=this.X;switch(a.keyCode){case 35:a.preventDefault();b=c.parentNode.lastChild;break;case 36:a.preventDefault();b=c.parentNode.firstChild;break;case 38:a.preventDefault();b=c.previousSibling;break;case 40:a.preventDefault();b=c.nextSibling;break;case 13:case 9:case 0:a.preventDefault();this.S();this.bb(c)}if(b&&b!=c){c.className="";b.className="goog-date-picker-menu-selected";this.X=b}};
p.S=function(){if(this.P){var a=xd(this);td(a,this.P,"click",this.yb);td(a,Cd(this,this.P),"key",this.zb);td(a,this.c.J,"click",this.S);wb(this.P);delete this.P}};function $(a,b,c,d,f){var e=["goog-date-picker-btn"];f&&e.push(f);f=a.c.createElement("button");f.className=e.join(" ");f.appendChild(a.c.createTextNode(c));b.appendChild(f);sd(xd(a),f,"click",function(g){g.preventDefault();d.call(this,g)});return f}
function Z(a){if(a.C()){var b=a.h.r();b.setDate(1);a.Ta&&H(a.Ta,pa("{$monthName} {$yearNum}",{monthName:a.p.aa[b.getMonth()],yearNum:b.getFullYear()}));a.K&&H(a.K,a.p.aa[b.getMonth()]);a.ea&&H(a.ea,String(b.getFullYear()));var c=((b.getDay()+6)%7-b.M+7)%7,d=Wc(b.getFullYear(),b.getMonth());b.add(new W(Yc,-1));b.setDate(Wc(b.getFullYear(),b.getMonth())-(c-1));a.Pb&&!a.vc&&d+c<33&&b.add(new W(Zc,-7));c=new W(Zc,1);a.n=[];for(d=0;d<6;d++){a.n[d]=[];for(var f=0;f<7;f++){a.n[d][f]=b.r();b.add(c)}}if(a.C()){b=
a.h.getMonth();f=new cd;c=f.getFullYear();d=f.getMonth();f=f.getDate();for(var e=0;e<6;e++){if(a.fb){var g=a.k[e+1][0],i=new Date(a.n[e][0].getFullYear(),a.n[e][0].getMonth(),a.n[e][0].getDate()),k=a.n[e][0].M||0,n=((i.getDay()+6)%7-k+7)%7;k=((a.n[e][0].ya||3)-k+7)%7;i=i.valueOf()+(k-n)*864E5;n=(new Date((new Date(i)).getFullYear(),0,1)).valueOf();H(g,Math.floor(Math.round((i-n)/864E5)/7)+1);a.k[e+1][0].className="goog-date-picker-week"}else{H(a.k[e+1][0],"");a.k[e+1][0].className=""}for(g=0;g<7;g++){i=
a.n[e][g];n=a.k[e+1][g+1];if(!n.id)n.id="goog-dp-"+Ad++;ed(n,"gridcell");k=["goog-date-picker-date"];if(a.Qc||i.getMonth()==b){i.getMonth()!=b&&k.push("goog-date-picker-other-month");var s=(g+a.h.M+7)%7;a.Ka[s]&&k.push(a.Ka[s]);i.getDate()==f&&i.getMonth()==d&&i.getFullYear()==c&&k.push("goog-date-picker-today");if(a.a&&i.getDate()==a.a.getDate()&&i.getMonth()==a.a.getMonth()&&i.getFullYear()==a.a.getFullYear()){k.push("goog-date-picker-selected");C&&a.gb.setAttribute("aria-activedescendant",n.id)}if(a.pb)(s=
a.pb(i))&&k.push(s);H(n,i.getDate())}else H(n,"");n.className=k.join(" ")}if(e>=4)pd(a.k[e+1][0].parentNode,a.n[e][0].getMonth()==b||a.Pb)}}}}function Cd(a,b){var c=w(b);c in a.V||(a.V[c]=new hd(b));return a.V[c]}function Bd(a,b,c){J.call(this,a,b);this.ta=c}x(Bd,J);u("myLog",function(a){function b(e,g){Nc("/logentriesjson/",function(i){i=Vc(i.target).entries;for(var k in i){i[k].content=i[k].content.replace(/&/g,"&amp;").replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/"/g,"&quot;");i[k].content=Ed(i[k].content)}if(!(i.length<=1)){k=F("log-table");for(var n='\t<table class="log-table"><tr><th class="timestamp-col">Time</th><th class="user-col">User</th><th class="content-col">Message</th></tr>',s={data:i}.data,r=s.length,o=0;o<r;o++){n=n;var t;t={Ua:s[o]};
t='<tr><td class="timestamp-cell">'+y(String(t.Ua.time))+'</td><td class="user-cell"><div class="user-container">'+y(String(t.Ua.user))+'</div></td><td class="content-cell">'+t.Ua.content+"</td></tr>";n=n+t}n+="</table>";k.innerHTML=n;d=e;f=e+i.length-1}},"POST","channelName="+encodeURIComponent(a)+"&limit="+g+"&offset="+e)}var c={},d,f;c.Pc=function(){b(f,10)};c.Oc=function(){var e=d-10+1;e<0||b(e,10)};b(0,10);F("olderlog-button").onclick=c.Pc;F("newerlog-button").onclick=c.Oc;return c},void 0);
function Ed(a){return a.replace(/\b[A-Z]+-[0-9]+\b/g,function(b){return'<a href="http://jira.mongodb.org/browse/'+b+'">'+b+"</a>"})}u("ticketFilter",Ed,void 0);
u("DatePicker",function(a){var b=document.getElementById(a);od=nd;var c=new Y;(function(){var d=document.createElement("table"),f=document.createElement("tr"),e=document.createElement("td"),g=document.createElement("td"),i=document.createElement("td"),k=document.createElement("td"),n=document.createElement("td"),s=document.createElement("td");d.appendChild(f);f.appendChild(e);f.appendChild(k);f.appendChild(g);f.appendChild(n);f.appendChild(i);f.appendChild(s);e.innerHTML=b.id+" label:";g.innerHTML=
"hour:";i.innerHTML="min:";f=document.createElement("input");f.type="text";f.size="10";f.name=b.id+"date";f.onclick=function(){c.style.visibility="visible"};k.appendChild(f);b.appendChild(d)})()},void 0);u("numbersDropdown",function(a,b,c){a=document.getElementById(a);for(var d=b;d<=c;d++){b=document.createElement("option");b.value=d>=10?d:"0"+d;b.text=d>=10?d:"0"+d;a.add(b)}},void 0);
u("setupDatePickers",function(){od=nd;var a=new Y;yd(a,F("start-date-picker"));P(a,"change",function(b){document.getElementById("start-date-text").value=b.ta?b.ta.Ia(j):"none";document.getElementById("start-date-picker").style.visibility="hidden"});a=new Y;yd(a,F("end-date-picker"));P(a,"change",function(b){document.getElementById("end-date-text").value=b.ta?b.ta.Ia(j):"none";document.getElementById("end-date-picker").style.visibility="hidden"})},void 0);function Fd(a,b,c){for(var d=G("ul","reasons"),f=0,e;e=c.reasons[f];f++){var g=G("li"),i=G("span","action"),k=i;e.action=="++"?db(k,"plusplus"):eb(k,"plusplus");k=i;e.action!="++"?db(k,"minusminus"):eb(k,"minusminus");i.innerHTML=e.action;g.appendChild(i);i=G("span",{},"'ed by ");g.appendChild(i);i=G("span","sender",e.sender);g.appendChild(i);i=e.reason.toLowerCase().indexOf(a.toLowerCase()+e.action);if(i!=-1){i=e.reason.substring(i+a.length+2);if(!/^[\s\xa0]*$/.test(i==l?"":String(i))){i=G("span",
{title:e.reason},i);g.appendChild(i)}}e=new Date(e.timestampMsec);e=G("span","date"," on "+((e.getMonth()+1<10?"0"+(e.getMonth()+1):e.getMonth()+1)+"/"+(e.getDate()<10?"0"+e.getDate():e.getDate())+"/"+e.getFullYear()));g.appendChild(e);d.appendChild(g)}a=G("img",{src:c.graph});d=G("div","target-details",a,d);b.appendChild(d)}u("addTargetDetails",Fd,void 0);
u("toggleTargetDetails",function(a,b,c){var d=a.parentNode,f=d.parentNode;fb(f,"target-expanded");if(pb(document,"div","target-details",d).length==0){db(f,"target-loading");Nc("/targetdetailsjson/"+b+"/"+c,function(e){eb(f,"target-loading");Fd(c,d,Vc(e.target))})}},void 0);function Gd(a,b){this.ca=a;this.oa=b;this.Sb()}Gd.prototype.Sb=function(){if(this.Ga==1){this.oa.reverse();Hd(this)}else{this.Ga=1;this.ba="&#9650;";this.oa.sort(function(a,b){return a.name.localeCompare(b.name)})}Id(this)};
function Hd(a){a.ba=a.ba=="&#9660;"?"&#9650;":"&#9660;"}Gd.prototype.Tc=function(){if(this.Ga==2){this.oa.reverse();Hd(this)}else{this.Ga=2;this.ba="&#9660;";this.oa.sort(function(a,b){return b.score-a.score})}Id(this)};
function Id(a){var b=F("score-table"),c={ca:a.ca,Wb:a.oa},d='<table class="channel-table"><tr><th class="target-cell" id="target-name-header" style="cursor: pointer; cursor: hand">Target</th><th class="score-cell" id="target-score-header" style="cursor: pointer; cursor: hand">Score</th></tr>';if(c.Wb.length==0)d+="<tr><td>No scores yet! Start ++'ing and --'ing stuff!</td></tr>";else for(var f=c.Wb,e=f.length,g=0;g<e;g++){d=d;var i;i={ca:c.ca,target:f[g]};i='<tr><td class="target-cell"><div class="target-name" onclick="toggleTargetDetails(this, \''+
y(String(i.ca))+"', '"+y(String(i.target.name))+"')\">"+y(String(i.target.name))+'</div></td><td class="score-cell">'+y(String(i.target.score))+"</td></tr>";d=d+i}d+="</table>";b.innerHTML=d;b=F("target-name-header");c=F("target-score-header");b.onclick=ma(a.Sb,a);c.onclick=ma(a.Tc,a);if(a.Ga==1)b.innerHTML=a.ba+b.innerHTML;else c.innerHTML=a.ba+c.innerHTML}u("partychapp.ScoreTable",Gd,void 0);function Jd(){this.fa=[];this.db=new gc;this.Zb=this.$b=this.ac=this.Tb=0;this.na=new gc;this.nb=this.Yb=0;this.cb=1;this.Wa=new L(0,4E3);this.Wa.da=function(){return new Kd};this.Ub=new L(0,50);this.Ub.da=function(){return new Ld};var a=this;this.Ya=new L(0,2E3);this.Ya.da=function(){return String(a.cb++)};this.Ya.Ra=function(){};this.uc=3}Jd.prototype.e=yc("goog.debug.Trace");function Ld(){this.hb=this.Xb=this.Qa=0}
Ld.prototype.toString=function(){var a=[];a.push(this.type," ",this.Qa," (",Math.round(this.Xb*10)/10," ms)");this.hb&&a.push(" [VarAlloc = ",this.hb,"]");return a.join("")};function Kd(){}function Md(a,b,c,d){var f=[];c==-1?f.push("    "):f.push(Nd(a.ub-c));f.push(" ",Od(a.ub-b));if(a.Xa==0)f.push(" Start        ");else if(a.Xa==1){f.push(" Done ");f.push(Nd(a.bd-a.startTime)," ms ")}else f.push(" Comment      ");f.push(d,a);a.Vc>0&&f.push("[VarAlloc ",a.Vc,"] ");return f.join("")}
Kd.prototype.toString=function(){return this.type==l?this.tc:"["+this.type+"] "+this.tc};Jd.prototype.reset=function(a){this.uc=a;for(a=0;a<this.fa.length;a++){var b=this.Wa.id;b&&M(this.Ya,b);M(this.Wa,this.fa[a])}this.fa.length=0;this.db.clear();this.Tb=oa();this.nb=this.Yb=this.Zb=this.$b=this.ac=0;b=this.na.ha();for(a=0;a<b.length;a++){var c=ic(this.na,b[a]);c.Qa=0;c.Xb=0;c.hb=0;M(this.Ub,c)}this.na.clear()};
Jd.prototype.toString=function(){for(var a=[],b=-1,c=[],d=0;d<this.fa.length;d++){var f=this.fa[d];f.Xa==1&&c.pop();a.push(" ",Md(f,this.Tb,b,c.join("")));b=f.ub;a.push("\n");f.Xa==0&&c.push("|  ")}if(this.db.i!=0){var e=oa();a.push(" Unstopped timers:\n");fc(this.db,function(g){a.push("  ",g," (",e-g.startTime," ms, started at ",Od(g.startTime),")\n")})}b=this.na.ha();for(d=0;d<b.length;d++){c=ic(this.na,b[d]);c.Qa>1&&a.push(" TOTAL ",c,"\n")}a.push("Total tracers created ",this.Yb,"\n","Total comments created ",
this.nb,"\n","Overhead start: ",this.ac," ms\n","Overhead end: ",this.$b," ms\n","Overhead comment: ",this.Zb," ms\n");return a.join("")};function Nd(a){a=Math.round(a);var b="";if(a<1E3)b=" ";if(a<100)b="  ";if(a<10)b="   ";return b+a}function Od(a){a=Math.round(a);return String(100+a/1E3%60).substring(1,3)+"."+String(1E3+a%1E3).substring(1,4)}new Jd;u("showCreateForm",function(){db(F("create-button-container"),"hidden");eb(F("channel-settings-table"),"hidden")},void 0);
u("submitCreateRoom",function(){var a=F("room-name").value,b=F("inviteonly-true").checked,c=F("invitees").value;if(/^[\s\xa0]*$/.test(a==l?"":String(a))){alert("Please enter a room name.");return m}Nc("/channel/create",function(d){var f=F("create-result");eb(f,"hidden");var e;d=d.target;try{e=d.d?d.d.responseText:""}catch(g){S(d.e,"Can not get responseText: "+g.message);e=""}f.innerHTML=e},"POST","name="+encodeURIComponent(a)+"&inviteonly="+b+"&invitees="+encodeURIComponent(c));return m},void 0);
u("acceptInvitation",function(a){window.location.href="/channel/invitation/accept?name="+encodeURIComponent(a)},void 0);u("declineInvitation",function(a){window.location.href="/channel/invitation/decline?name="+encodeURIComponent(a)},void 0);u("requestInvitation",function(a){window.location.href="/channel/invitation/request?name="+encodeURIComponent(a)},void 0);u("getInvitation",function(a){window.location.href="/channel/invitation/get?name="+encodeURIComponent(a)},void 0);
u("displayChannels",function(a,b){b.setAttribute("style","display: block");if(a.error)b.innerHTML="ERROR: "+a.error;else{for(var c=G("ul","channel-list"),d=a.channels,f=0,e;e=d[f];f++){var g=G("a",{href:"/channel/"+e.name},e.name);e=G("span","description"," as ",G("b",{},e.alias),e.memberCount>1?" with "+(e.memberCount-1)+(e.memberCount==2?" other":" others"):"");g=G("li",{},g,e);c.appendChild(g)}b.appendChild(c)}},void 0);
u("printEmail",function(a){for(var b=[112,97,114,116,121,99,104,97,112,112,64,103,111,111,103,108,101,103,114,111,117,112,115,46,99,111,109],c=[],d=0;d<b.length;d++)c.push(String.fromCharCode(b[d]));c=c.join("");document.write('<a href="mailto:'+c+'">'+(a||c)+"</a>")},void 0);
